PELE_PHYSICS_HOME=/Users/terencelehmann/Applications/Pele/PelePhysics
AMREX_HOME=/Users/terencelehmann/Applications/Pele/PelePhysics/Submodules/amrex
USE_UTILS=TRUE
include $(abspath ../../Src/GNUmakefile)
